[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "astralix-tl"
dynamic = ["version"]
description = "This library is built for the astralix Userbot and is based on Telethon."
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE.md", "NOTICE.md"]
requires-python = ">=3.10"
maintainers = [{ name = "LowSense" }]
authors = [
    { name = "Codrago", email = "codrago@xyecoc.com" },
]
keywords = [
    "api",
    "chat",
    "client",
    "library",
    "messaging",
    "mtproto",
    "telegram",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
dependencies = [
    "pyaes",
    "rsa",
    "bs4==0.0.2",
]

[project.optional-dependencies]
cryptg = [
    "cryptg",
]

[project.urls]
Homepage = "https://astralix.cc"
Source = "https://git.astralix.cc/lowsense-dev/astralix-tl"
Documentation = "https://docs.telethon.dev"
Reference = "https://tl.telethon.dev"

[tool.hatch.version]
path = "astralixtl/version.py"

[tool.hatch.build.targets.sdist]
include = [
    "/astralixtl",
    "/telethon_generator",
    "/hatch_build.py",
    "/README.md",
    "/NOTICE.md",
    "/LICENSE.md",
    "/tests",
]

[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.wheel]
packages = ["astralixtl"]
